### ISSUE TITLE
Tensorflow error 

### ISSUE THREAD

**Issue by MaxenceGiraud** [leonhart8/alpha_zero#1]
Got a tensorflow error when trying to play tictactoe again this wonderful algorithm

```bash

2021-01-07 15:45:09.887813: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2021-01-07 15:45:09.887952: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2021-01-07 15:45:09.887968: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2021-01-07 15:45:11.029581: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-01-07 15:45:11.096656: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-01-07 15:45:11.096704: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (dellmaxpop): /proc/driver/nvidia/version does not exist
2021-01-07 15:45:11.097162: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-01-07 15:45:11.106826: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2599990000 Hz
2021-01-07 15:45:11.107480: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x558279994ea0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-01-07 15:45:11.107507: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "play.py", line 129, in <module>
    play.human_vs_ai("best_net")
  File "play.py", line 86, in human_vs_ai
    model = keras.models.load_model(pathname)
  File "/home/max/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 150, in load_model
    return saved_model_load.load(filepath, compile)
  File "/home/max/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 99, in load
    training_config))
  File "/home/max/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saving_utils.py", line 242, in compile_args_from_training_config
    sample_weight_mode = training_config['sample_weight_mode']
KeyError: 'sample_weight_mode'

```

(it may be a problem on my side, did not check very thoroughly)

**Comment by MaxenceGiraud** [comment]
Was an error on my part, project is not compatible with tensorflow 2.1
